baseURL = 'https://myl3z.me/'
languageCode = 'de-de'
title = 'myl3z.me - CyberSec - Dev - Server'

theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2