baseURL = 'https://myl3z.me/'
languageCode = 'de-de'
title = 'myl3z.me - CyberSec - Dev - Server'

theme = "terminal"

[languages]
  [languages.en]
    title = "myl3z.me - My Notes"
    subtitle = "Just my notes"
    keywords = ""
    copyright = "xander"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
